Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -45,5 +45,9 @@ jobs:
          nvm use 21.7.1
          cd portfolio
          npm install 
-         npm run build
+         npm run build --verbose
+         if [ ! -d ".next" ]; then
+           echo ".next directory not found! Exiting."
+           exit 1
+         fi
          pm2 restart portfolio
